/*
    Copyright 2010 University of Twente and Delft University of Technology
 
       This file is part of the Mapping libraries and tools, developed
  for research, education and projects in photogrammetry and laser scanning.

  The Mapping libraries and tools are free software: you can redistribute it
    and/or modify it under the terms of the GNU General Public License as
  published by the Free Software Foundation, either version 3 of the License,
                   or (at your option) any later version.

 The Mapping libraries and tools are distributed in the hope that it will be
    useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
                GNU General Public License for more details.

      You should have received a copy of the GNU General Public License
          along with the Mapping libraries and tools.  If not, see
                      <http://www.gnu.org/licenses/>.

----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "Database.h"
#include "stdmath.h"
#include "viff.h"

/*-----------------------------------------------------------
|
|    Written By: R.Th. Ursem
|          Date: Jul 27, 1999
| Modifications:
|
------------------------------------------------------------*/

#define READINPUT(image, name, program) \
  image = readimage(name);  \
  if (image == NULL) {  \
    (void) fprintf(stderr, "%s: Can not read input image %s.\n", program, name);  \
    exit(1);  /* Quit if bad image */ \
  }

#define TRUE 1
  
#define CHECKINPUT(program, img1, img2) \
  (void) proper_num_images(program,img1,1,TRUE); \
  (void) proper_num_images(program,img2,1,TRUE); \
  \
  (void) proper_num_bands(program,img1,1,TRUE); \
  (void) proper_num_bands(program,img2,1,TRUE); \
  \
  (void) proper_map_enable(program,img1,VFF_MAP_OPTIONAL,TRUE); \
  (void) proper_map_enable(program,img2,VFF_MAP_OPTIONAL,TRUE);


int anaglyph_c(char *i1_file, char *i2_file, char *o_file,
               int left_band, int right_band, int dr, int dc)
{
  xvimage *left, *right, *blended, *readimage(), *createimage();
  char message[256];
  int w, h, i;
 
  sprintf(message, "\tLeft image was %s\n\tright image was %s", 
          i1_file, i2_file);

  READINPUT(left,  i1_file, "anaglyph");
  READINPUT(right, i2_file, "anaglyph");

  CHECKINPUT("anaglyph", left, right);

  w = MAX(left->row_size, right->row_size) + abs(dc);
  h = MAX(left->col_size, right->col_size) + abs(dr);
  
  printf("%s\n\n", "anaglyph");
  
  printf("  %s\n  %s\n  ", i1_file, i2_file);
  for (i = 0; i < MAX( strlen(i1_file), strlen(i2_file) ); i++)
     printf("-");
  printf(" +\n");
  printf("  %s\n\n", o_file);
  
  printf("  offset in row direction : %3d pixels\n",   dr);
  printf("  offset in col direction : %3d pixels\n\n", dc);
  
  printf("  Image size will be (%dx%d)\n", h, w);
  
  sprintf(message, "Offset in row direction : %3d\nOffset in col direction : %3d\
\nGenerated by %s", dr, dc, "anaglyph");
  
  blended = createimage(h, w,            /* size of the image           */
                     VFF_TYP_1_BYTE,     /* data storage type           */
                     1, 3,               /* one image, three bands      */
                     message,            /* comment                     */
                     0,                  /* map row size (none)         */
                     0,                  /* map col size (none)         */
                     VFF_MS_NONE,        /* map scheme                  */
                     VFF_MAPTYP_NONE,    /* map storage type            */
                     VFF_LOC_IMPLICIT,   /* location type               */
                     0);                 /* location dimension          */
  if (blended == NULL) 
    {
    fprintf( stderr, "Not enough memory for resulting image\n");
    exit(1);
    }
    
  blended->color_space_model = VFF_CM_genericRGB;

  if (!lanaglyph(left, right, blended, left_band, right_band, dr, dc))
    {
    fprintf( stderr, "l%s error\n", "anaglyph");
    exit(1);
    }

  printf("\nWriting resulting file to %s\n", o_file);
  writeimage(o_file, blended);

  return 1;
}
